# Generated by Django 5.1 on 2024-09-23 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('Deptno', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('Dept_name', models.CharField(max_length=20)),
                ('Dept_loc', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('Empno', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('Emp_name', models.CharField(max_length=25)),
                ('comm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Sal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
                ('Mgr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employees')),
            ],
        ),
    ]
