# Generated by Django 5.1 on 2024-09-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='Hire_date',
            field=models.DateField(auto_now_add=True, default='1991-10-10'),
            preserve_default=False,
        ),
    ]
